# Generated by Django 4.2.16 on 2024-10-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trainingschedule_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], max_length=50, null=True),
        ),
    ]
